# Generated by Django 2.2.4 on 2019-09-05 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='phone_numer',
            field=models.CharField(default='080', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='order_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Address'),
        ),
    ]
