# Generated by Django 2.2.4 on 2019-09-06 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190905_1924'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='phone_numer',
            new_name='phone_number',
        ),
    ]
